
const assert=require("node:assert/strict");
const fs=require("node:fs");
const ts=require("typescript");
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||"playwright");
const base=process.env.TEST_BASE_URL||"http://127.0.0.1:3000";
const output={exports:{}};
new Function("module","exports",ts.transpileModule(fs.readFileSync("lib/profile.ts","utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(output,output.exports);
const fixture={...output.exports.initial,name:"Hồ sơ kiểm thử",email:"test@example.com"};
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
 try {
  const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:"reduce"});
  const page=await context.newPage();
  const errors=[];page.on("pageerror",error=>errors.push(error.message));
  await page.goto(base);
  await page.evaluate(p=>localStorage.setItem("portfolio-studio-draft-v1",JSON.stringify(p)),fixture);
  await page.reload();
  await page.getByRole("link",{name:"Sơ yếu lý lịch ↗",exact:true}).click();
  await page.waitForURL("**/so-yeu-ly-lich");
  await page.getByRole("heading",{name:"Sơ yếu lý lịch.",exact:true}).waitFor();
  await page.getByRole("heading",{name:"Sơ yếu lý lịch.",exact:true}).waitFor();
  await page.getByRole("button",{name:"Chỉnh sửa",exact:true}).click();
  assert.equal(await page.getByRole("tab",{name:"Sơ yếu lý lịch",exact:true}).getAttribute("aria-selected"),"true");
  const png=await page.evaluate(()=>{const canvas=document.createElement("canvas");canvas.width=600;canvas.height=400;const ctx=canvas.getContext("2d");ctx.fillStyle="#b5f5d1";ctx.fillRect(0,0,600,400);ctx.fillStyle="#17251c";ctx.fillRect(200,100,200,200);return canvas.toDataURL("image/png").split(",")[1];});
  await page.getByLabel("Tải ảnh đại diện",{exact:true}).setInputFiles({name:"avatar.png",mimeType:"image/png",buffer:Buffer.from(png,"base64")});
  await page.getByRole("button",{name:"Xóa ảnh",exact:true}).waitFor();
  await page.getByLabel("Ngày sinh",{exact:true}).fill("13/09/1995");
  await page.getByLabel("Sở thích",{exact:true}).fill("Đọc sách, chạy bộ 🌱");
  await page.getByLabel("Đam mê",{exact:true}).fill("Xây dựng sản phẩm có ích");
  await page.getByLabel("Tính cách",{exact:true}).fill("Điềm tĩnh và tò mò");
  await page.getByLabel("Tình trạng hôn nhân",{exact:true}).fill("Thông tin mẫu");
  await page.getByLabel("Sức khỏe",{exact:true}).fill("Ghi chú sức khỏe mẫu");
  await page.getByRole("button",{name:"Thêm thành viên",exact:true}).click();
  await page.getByLabel("Họ và tên",{exact:true}).fill("Thành viên mẫu");
  await page.getByLabel("Mối quan hệ",{exact:true}).fill("Anh/chị");
  await page.getByLabel("Nghề nghiệp",{exact:true}).fill("Kỹ sư");
  await page.locator(".editor-item").getByLabel("Học vấn",{exact:true}).fill("Đại học — Công nghệ thông tin");
  await page.getByRole("button",{name:"Thêm thành viên",exact:true}).click();
  await page.getByRole("button",{name:"Thêm thông tin",exact:true}).click();
  await page.getByLabel("Tên mục",{exact:true}).fill("Ngoại ngữ");
  await page.getByLabel("Nội dung",{exact:true}).fill("Tiếng Việt, English");
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"Mobile editor overflow");
  await page.getByRole("button",{name:"Lưu thay đổi",exact:true}).click();
  await page.getByText("Đọc sách, chạy bộ 🌱",{exact:true}).waitFor();
  await page.reload();
  await page.getByText("Thành viên mẫu",{exact:true}).waitFor();
  await page.getByText("Đại học — Công nghệ thông tin",{exact:true}).waitFor();
  await page.waitForFunction(()=>document.querySelector(".bio-identity .bio-avatar img")?.naturalWidth>0);
  assert.equal(await page.locator(".bio-family-member").count(),1);
  assert.equal(await page.locator(".bio-family-member dt").filter({hasText:"Năm sinh"}).count(),0);
  assert.equal(await page.locator(".bio-family-member dt").filter({hasText:"Thông tin thêm"}).count(),0);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"Mobile page overflow");
  fs.mkdirSync(".data",{recursive:true});
  await page.screenshot({path:".data/biography-mobile.png",fullPage:true});
  await page.getByRole("link",{name:"Về trang portfolio",exact:true}).click();
  await page.getByRole("button",{name:"Gửi HR",exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.share-dialog input')?.value.includes('?s='));
  const link=await page.locator('.share-dialog input').inputValue();
  const hrContext=await browser.newContext({viewport:{width:1440,height:1000}});
  const hr=await hrContext.newPage();
  await hr.goto(link);
  await hr.getByRole("link",{name:"Sơ yếu lý lịch ↗",exact:true}).click();
  await hr.getByText("Thành viên mẫu",{exact:true}).waitFor();
  await hr.getByText("Đại học — Công nghệ thông tin",{exact:true}).waitFor();
  await hr.waitForFunction(()=>document.querySelector(".bio-identity .bio-avatar img")?.naturalWidth>0);
  assert.equal(new URL(hr.url()).search,new URL(link).search);
  assert.equal(await hr.getByRole("button",{name:"Chỉnh sửa",exact:true}).count(),0);
  await hr.emulateMedia({reducedMotion:"reduce"});
  await hr.screenshot({path:".data/biography-desktop.png",fullPage:true});
  await hr.getByRole("link",{name:"Về trang portfolio",exact:true}).click();
  assert.equal(new URL(hr.url()).search,new URL(link).search);
  await page.getByRole("dialog").getByRole("button",{name:/Close|Đóng/}).click();
  await page.getByRole("link",{name:"Sơ yếu lý lịch ↗",exact:true}).click();
  await page.waitForURL("**/so-yeu-ly-lich");
  await page.getByRole("heading",{name:"Sơ yếu lý lịch.",exact:true}).waitFor();
  await page.getByRole("button",{name:"Chỉnh sửa",exact:true}).click();
  await page.getByRole("button",{name:"Xóa ảnh",exact:true}).click();
  await page.getByLabel("Tải ảnh đại diện",{exact:true}).setInputFiles({name:"bad.txt",mimeType:"text/plain",buffer:Buffer.from("not an image")});
  await page.getByText("Vui lòng chọn ảnh JPG, PNG hoặc WebP.",{exact:true}).waitFor();
  await page.getByLabel("Sức khỏe",{exact:true}).fill("Đã cập nhật bản nháp");
  await page.getByRole("button",{name:"Xóa thành viên 1",exact:true}).click();
  await page.getByRole("button",{name:"Lưu thay đổi",exact:true}).click();
  await page.getByText("Đã cập nhật bản nháp",{exact:true}).waitFor();
  assert.equal(await page.locator(".bio-identity .bio-avatar img").count(),0);
  await hr.goto(base+"/so-yeu-ly-lich"+new URL(link).search);
  await hr.getByText("Ghi chú sức khỏe mẫu",{exact:true}).waitFor();
  await hr.getByText("Thành viên mẫu",{exact:true}).waitFor();
  const encoded=require("lz-string").compressToEncodedURIComponent(JSON.stringify(fixture));
  await hr.goto(base+"/so-yeu-ly-lich#p="+encoded);
  await hr.getByText("Chưa có thông tin bổ sung.",{exact:true}).waitFor();
  assert.equal(await hr.getByRole("button",{name:"Chỉnh sửa",exact:true}).count(),0);
  await hr.getByRole("link",{name:"Về trang portfolio",exact:true}).click();
  assert.equal(new URL(hr.url()).hash,"#p="+encoded);
  await page.goto(base+"/so-yeu-ly-lich");
  await page.evaluate(p=>localStorage.setItem("portfolio-studio-draft-v1",JSON.stringify(p)),{...fixture,biography:{...output.exports.emptyBiography(),health:"   ",family:[{name:"",relationship:"",birthYear:"",occupation:"",education:"  ",notes:""}]}});
  await page.reload();
  await page.getByText("Chưa có thông tin bổ sung.",{exact:true}).waitFor();
  assert.equal(await page.locator("section.bio-card").count(),0);
  assert.equal(await page.locator(".bio-nav a").count(),0);
  assert.equal(await page.getByRole("button",{name:"Chỉnh sửa",exact:true}).count(),1);
  assert.deepEqual(errors,[]);
  console.log("Browser checks passed: mobile layout, editing all biography groups, save/reload, family removal, footer links, HR read-only view, snapshot persistence, legacy sharing, no client errors.");
 } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
