const assert = require("node:assert/strict");
const fs = require("node:fs");
const ts = require("typescript");
function load(file, overrides={}) {
 const source = ts.transpileModule(fs.readFileSync(file,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;
 const module={exports:{}};
 new Function("require","module","exports",source)(name=>overrides[name]||require(name),module,module.exports);
 return module.exports;
}
const profile=load("lib/profile.ts");
const sharing=load("lib/sharing.ts",{"./profile":profile});
const p=structuredClone(profile.initial);
p.name="Trần Ánh 🌱";p.about="Kỹ sư phần mềm\nTôi yêu TypeScript & thiết kế.";
const encoded=sharing.encodeProfile(p);
assert.deepEqual(sharing.decodeProfile(encoded),p);
assert.equal(profile.safeUrl("javascript:alert(1)"),"");
assert.throws(()=>sharing.validateProfile({...p,email:"wrong"}));
assert.throws(()=>sharing.validateProfile({...p,cv:"data:text/html,hello"}));
assert.throws(()=>sharing.validateProfile({...p,projects:[{...p.projects[0],url:"javascript:alert(1)"}]}));
assert.throws(()=>sharing.decodeProfile("broken-data"));
assert.throws(()=>sharing.decodeProfile("a".repeat(55001)));
assert.throws(()=>sharing.validateProfile({...p,experience:Array(13).fill(p.experience[0])}));
assert.throws(()=>sharing.validateProfile({...p,skills:42}));
const oldLink=sharing.encodeProfile(p);p.name="Đã chỉnh sửa";assert.notEqual(sharing.decodeProfile(oldLink).name,p.name);
assert.deepEqual(sharing.validateProfile({...p,projects:[],experience:[]}).projects,[]);
console.log("11 checks passed: Unicode round trip, URL/email validation, malformed payloads, list limits, immutable shares, empty lists.");

// Biography data must survive backups and shares without changing legacy payloads.
const bio=profile.emptyBiography();
assert.equal(bio.health, "");
assert.equal(bio.maritalStatus, "");
bio.birthDate="13/09/1995";
bio.interests="Đọc sách, chạy bộ 🌱";
bio.passions="Xây dựng sản phẩm";
bio.personality="Điềm tĩnh, tò mò";
bio.health="Thông tin sức khỏe mẫu";
bio.maritalStatus="Thông tin mẫu";
bio.family=[{name:"Thành viên mẫu",relationship:"Anh/chị",birthYear:"1990",occupation:"Kỹ sư",notes:"Ghi chú mẫu"}];
bio.customFields=[{label:"Ngoại ngữ",value:"Tiếng Việt, English"}];
const withBio={...p,biography:bio};
assert.deepEqual(sharing.decodeProfile(sharing.encodeProfile(withBio)),withBio);
assert.deepEqual(sharing.validateProfile(JSON.parse(JSON.stringify(withBio))),withBio);
assert.equal(Object.hasOwn(sharing.validateProfile(p),"biography"),false);
const snapshot=sharing.encodeProfile(withBio);
withBio.biography.family[0].name="Đã đổi";
assert.equal(sharing.decodeProfile(snapshot).biography.family[0].name,"Thành viên mẫu");
assert.throws(()=>sharing.validateProfile({...p,biography:[]}));
assert.throws(()=>sharing.validateProfile({...p,biography:{health:42}}));
assert.throws(()=>sharing.validateProfile({...p,biography:{notes:"x".repeat(5001)}}));
assert.throws(()=>sharing.validateProfile({...p,biography:{family:Array(13).fill(bio.family[0])}}));
assert.throws(()=>sharing.validateProfile({...p,biography:{family:[{name:"Incomplete"}]}}));
assert.throws(()=>sharing.validateProfile({...p,biography:{customFields:[{label:"Bad",value:42}]}}));
assert.throws(()=>sharing.validateProfile({...p,biography:{customFields:Array(13).fill({label:"a",value:"b"})}}));
assert.equal(sharing.validateProfile({...p,biography:{health:"",unknown:"drop"}}).biography.unknown,undefined);
assert.throws(()=>sharing.validateProfile({...p,biography:Object.fromEntries(profile.biographyFields.map(([key])=>[key,"x".repeat(5000)]))}));
assert.equal(sharing.profilePageHref("/so-yeu-ly-lich","?s=abc123","#family"),"/so-yeu-ly-lich?s=abc123");
assert.equal(sharing.profilePageHref("/","?s=abc123","#family"),"/?s=abc123");
assert.equal(sharing.profilePageHref("/so-yeu-ly-lich","","#p=legacy"),"/so-yeu-ly-lich#p=legacy");
assert.equal(sharing.profilePageHref("/","","#p=legacy"),"/#p=legacy");
assert.equal(sharing.profilePageHref("/so-yeu-ly-lich","","#about"),"/so-yeu-ly-lich");
assert.equal(sharing.profilePageHref("/","?s=",""),"/?s=");
console.log("Biography checks passed: round trips, legacy compatibility, immutable shares, validation, size limits and navigation between shared pages.");

const familyEducation={...p,biography:{...profile.emptyBiography(),family:[{name:"Sample",relationship:"Sibling",birthYear:"",occupation:"",education:"Đại học",notes:""}]}};
assert.deepEqual(sharing.decodeProfile(sharing.encodeProfile(familyEducation)),familyEducation);
assert.throws(()=>sharing.validateProfile({...familyEducation,biography:{...familyEducation.biography,family:[{...familyEducation.biography.family[0],education:42}]}}));
assert.throws(()=>sharing.validateProfile({...familyEducation,biography:{...familyEducation.biography,family:[{...familyEducation.biography.family[0],education:"x".repeat(5001)}]}}));
console.log("Family education checks passed: round trip, validation and legacy family snapshots.");

const avatar="data:image/jpeg;base64,/9j/2Q==";
assert.deepEqual(sharing.decodeProfile(sharing.encodeProfile({...p,avatar})),{...p,avatar});
assert.equal(sharing.validateProfile({...p,avatar:""}).avatar,"");
for(const avatar of [42,"https://example.com/photo.jpg","data:image/svg+xml;base64,PHN2Zz4=","data:image/jpeg;base64,"+"a".repeat(32000)])assert.throws(()=>sharing.validateProfile({...p,avatar}));
console.log("Avatar checks passed: snapshot round trip, removal, type, format and size validation.");
