"use client";
import { useState, type ChangeEvent } from "react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Checkbox } from "@/components/ui/checkbox";
import { Plus, Trash2, Save, Copy, Download, Upload, Check, ArrowUpRight } from "lucide-react";
import { type Profile } from "@/lib/profile";
import { DRAFT_KEY, validateProfile, profileLink } from "@/lib/sharing";
type Props={open:boolean;onOpenChange:(open:boolean)=>void;profile:Profile;onSave:(p:Profile)=>void};
function Field({label,value,onChange,multiline=false,type="text",required=false}:{label:string;value:string;onChange:(s:string)=>void;multiline?:boolean;type?:string;required?:boolean}){return <label className="editor-field"><span>{label}{required?" *":""}</span>{multiline?<textarea value={value} onChange={e=>onChange(e.target.value)} rows={3} maxLength={5000} required={required}/>:<input type={type} value={value} onChange={e=>onChange(e.target.value)} maxLength={5000} required={required}/>}</label>}
export function Editor({open,onOpenChange,profile,onSave}:Props){
 const [draft,setDraft]=useState<Profile>(()=>structuredClone(profile));const [error,setError]=useState("");
 const field=(k:keyof Profile,v:unknown)=>setDraft(p=>({...p,[k]:v}));
 const save=()=>{try{const next=validateProfile(draft);localStorage.setItem(DRAFT_KEY,JSON.stringify(next));onSave(next);onOpenChange(false);}catch(e){setError(e instanceof Error?e.message:"Không thể lưu trên trình duyệt này. Hãy xuất bản sao JSON.");}};
 const exportDraft=()=>{const blob=new Blob([JSON.stringify(draft,null,2)],{type:"application/json"});const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download="portfolio-backup.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
 const importDraft=async(e:ChangeEvent<HTMLInputElement>)=>{try{const file=e.target.files?.[0];if(!file)return;if(file.size>150000)throw new Error("Tệp quá lớn.");const p=validateProfile(JSON.parse(await file.text()));setDraft(p);setError("");}catch(err){setError(err instanceof Error?err.message:"Không thể đọc tệp.");}e.target.value=""};
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="editor-dialog"><DialogTitle className="editor-title">Không ai kể câu chuyện của bạn tốt hơn bạn.</DialogTitle><DialogDescription>Chỉnh sửa hồ sơ, lưu trên thiết bị này, rồi tạo link gửi HR. Các thông tin ban đầu là nội dung mẫu.</DialogDescription>
 <form onSubmit={e=>{e.preventDefault();save()}}><Tabs defaultValue="profile"><TabsList className="editor-tabs"><TabsTrigger value="profile">Thông tin</TabsTrigger><TabsTrigger value="projects">Dự án ({draft.projects.length})</TabsTrigger><TabsTrigger value="experience">Kinh nghiệm</TabsTrigger><TabsTrigger value="links">Liên kết</TabsTrigger></TabsList><div className="editor-scroll">
 <TabsContent value="profile"><div className="editor-grid"><Field label="Họ và tên" required value={draft.name} onChange={v=>field("name",v)}/><Field label="Vị trí chuyên môn" required value={draft.role} onChange={v=>field("role",v)}/><Field label="Địa điểm" value={draft.location} onChange={v=>field("location",v)}/><Field label="Số năm kinh nghiệm" value={draft.years} onChange={v=>field("years",v)}/></div><Field label="Giới thiệu ngắn" multiline value={draft.intro} onChange={v=>field("intro",v)}/><Field label="Về bạn" multiline value={draft.about} onChange={v=>field("about",v)}/><Field label="Kỹ năng (ngăn cách bằng dấu phẩy)" value={draft.skills} onChange={v=>field("skills",v)}/><label className="available-field"><Checkbox checked={draft.available} onCheckedChange={checked=>field("available",checked)}/>Sẵn sàng cho cơ hội mới</label></TabsContent>
 <TabsContent value="projects">{draft.projects.map((p,i)=><div className="editor-item" key={i}><div className="item-heading"><b>Dự án {i+1}</b><button type="button" aria-label={"Xóa dự án "+(i+1)} onClick={()=>field("projects",draft.projects.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div>{([["title","Tên dự án"],["category","Vai trò / Loại dự án"],["description","Mô tả đóng góp"],["tags","Công nghệ (dấu phẩy)"],["result","Kết quả / Điểm nổi bật"],["url","Link dự án hoặc GitHub"]] as const).map(([k,label])=><Field key={k} label={label} type={k==="url"?"url":"text"} multiline={k==="description"} value={p[k]} onChange={v=>field("projects",draft.projects.map((item,j)=>j===i?{...item,[k]:v}:item))}/>)}</div>)}<button type="button" className="btn subtle add-item" disabled={draft.projects.length>=12} onClick={()=>field("projects",[...draft.projects,{title:"Dự án mới",category:"",description:"",tags:"",result:"",url:""}])}><Plus size={16}/>Thêm dự án</button></TabsContent>
 <TabsContent value="experience">{draft.experience.map((p,i)=><div className="editor-item" key={i}><div className="item-heading"><b>Kinh nghiệm {i+1}</b><button type="button" aria-label={"Xóa kinh nghiệm "+(i+1)} onClick={()=>field("experience",draft.experience.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div>{([["company","Công ty"],["role","Vị trí"],["period","Thời gian"],["description","Trách nhiệm và thành tựu"]] as const).map(([k,label])=><Field key={k} label={label} multiline={k==="description"} value={p[k]} onChange={v=>field("experience",draft.experience.map((item,j)=>j===i?{...item,[k]:v}:item))}/>)}</div>)}<button type="button" className="btn subtle add-item" disabled={draft.experience.length>=12} onClick={()=>field("experience",[...draft.experience,{company:"Công ty",role:"",period:"",description:""}])}><Plus size={16}/>Thêm kinh nghiệm</button></TabsContent>
 <TabsContent value="links"><Field label="Email liên hệ" type="email" required value={draft.email} onChange={v=>field("email",v)}/>{([["github","GitHub"],["linkedin","LinkedIn"],["cv","Link CV (PDF công khai hoặc Google Drive)"]] as const).map(([k,label])=><Field key={k} label={label} type="url" value={draft[k]} onChange={v=>field(k,v)}/>)}<p className="field-help">Để trống liên kết chưa có. Đảm bảo HR được phép xem tệp CV trước khi chia sẻ.</p><div className="backup-controls"><button type="button" className="btn subtle" onClick={exportDraft}><Download size={16}/>Xuất bản sao</button><label className="btn subtle import-label"><Upload size={16}/>Nhập bản sao<input type="file" accept=".json,application/json" onChange={importDraft}/></label></div></TabsContent>
 </div></Tabs>{error&&<p role="alert" className="form-error">{error}</p>}<div className="editor-footer"><span>Bản nháp lưu riêng trên trình duyệt này.</span><button type="submit" className="btn primary"><Save size={16}/>Lưu thay đổi</button></div></form></DialogContent></Dialog>;
}
export function ShareDialog({open,onOpenChange,profile}:Omit<Props,"onSave">){
 const [copied,setCopied]=useState(false);const [error,setError]=useState("");const link=typeof window!=="undefined"?profileLink(profile):"";
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="share-dialog"><DialogTitle className="editor-title">Sẵn sàng cho cơ hội tiếp theo.</DialogTitle><DialogDescription>Link chứa một bản hồ sơ chỉ xem. Sau khi chỉnh sửa thêm, hãy tạo và gửi link mới. Người có link có thể đọc toàn bộ nội dung hồ sơ.</DialogDescription><label className="editor-field"><span>Link hồ sơ gửi HR</span><textarea rows={3} readOnly value={link} onFocus={e=>e.target.select()}/></label><div className="share-actions"><button className="btn primary" onClick={async()=>{try{await navigator.clipboard.writeText(link);setCopied(true)}catch{setError("Hãy chọn và sao chép toàn bộ link trong ô phía trên.")}}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?"Đã sao chép":"Sao chép link"}</button><a className="btn subtle" target="_blank" rel="noreferrer" href={link}>Mở bản HR <ArrowUpRight size={16}/></a></div>{error&&<p role="alert" className="form-error">{error}</p>}<p className="field-help">Link giữ nguyên nội dung tại thời điểm tạo. Nếu website yêu cầu đăng nhập, cần cấp quyền truy cập website cho HR trước.</p></DialogContent></Dialog>;
}

